spring.datasource.url: jdbc:mysql://localhost:3306/search_engine
spring.datasource.username: root
spring.datasource.password: 12345
spring.sql.init.mode: always
spring.jpa.hibernate.ddl-auto: none
spring.jpa.show-sql: false

logging.level.root: info
spring.output.ansi.enabled: ALWAYS

searchbot.threadNumber: 3
searchbot.userAgent: KaleganovSearchBot-1.0
searchbot.pathToWebInterface: /admin
searchbot.links:
#  - url: http://www.playback.ru/
#    name: Playback
  - url: https://nikoartgallery.com
    name: Галерея Исскуств Нико
  - url: http://radiomv.ru/
    name: Радио Милицейская Волна
  - url: https://www.svetlovka.ru
    name: Библиотека Светловка
  - url: https://www.lutherancathedral.ru
    name: Собор святых Петра и Павла