DROP TABLE IF EXISTS pages;
DROP TABLE IF EXISTS fields;
DROP TABLE IF EXISTS lemmas;
DROP TABLE IF EXISTS indexes;

CREATE TABLE  pages(
id INT AUTO_INCREMENT PRIMARY KEY,
path TEXT NOT NULL,
code INT NOT NULL,
content  MEDIUMTEXT NOT NULL,
KEY (path(50))
);

CREATE TABLE fields(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    selector VARCHAR(255) NOT NULL,
    weight FLOAT NOT NULL
);

CREATE TABLE lemmas(
    id INT AUTO_INCREMENT PRIMARY KEY,
    lemma VARCHAR(255) NOT NULL UNIQUE KEY,
    frequency INT NOT NULL
);

CREATE TABLE indexes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    page_id INT NOT NULL,
    lemma_id INT NOT NULL,
    `rank` FLOAT NOT NULL
);