DROP TABLE IF EXISTS pages;
DROP TABLE IF EXISTS fields;
DROP TABLE IF EXISTS lemmas;
DROP TABLE IF EXISTS indexes;
DROP TABLE IF EXISTS sites;

CREATE TABLE  pages(
id INT AUTO_INCREMENT PRIMARY KEY,
site_id INT NOT NULL,
path TEXT NOT NULL,
code INT NOT NULL,
content  MEDIUMTEXT NOT NULL,
KEY (path(50))
);

CREATE TABLE fields(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    selector VARCHAR(255) NOT NULL,
    weight FLOAT NOT NULL
);

CREATE TABLE lemmas(
    id INT AUTO_INCREMENT PRIMARY KEY,
    site_id INT NOT NULL,
    lemma VARCHAR(255) NOT NULL,
    frequency INT NOT NULL,
    UNIQUE KEY (site_id, lemma)
);

CREATE TABLE indexes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    page_id INT NOT NULL,
    lemma_id INT NOT NULL,
    `rank` FLOAT NOT NULL
);

CREATE TABLE sites (
    id INT AUTO_INCREMENT PRIMARY KEY,
    status ENUM ('INDEXING', 'INDEXED', 'FAILED') NOT NULL,
    status_time DATETIME NOT NULL,
    last_error TEXT,
    url VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL
);